### ISSUE TITLE
League of Legends script doesn't work

### ISSUE THREAD

**Issue by Sylvert0** [PhoenicisOrg/scripts#464]
- The installer hash are wrong.

Once i fix the installer hash, i get this: 
![LoL](https://i.imgur.com/hBqQVuZ.png)

**Comment by plata** [comment]
Can you provide a pull request which fixes this?

**Comment by Sylvert0** [comment]
I dont know how to fix it, i can't get the .msi file

**Comment by Sylvert0** [comment]
Here is what i have: https://pastebin.com/irkru9xH

But i can't call the LoL.exe on installationCommand after dx9 and vcrun2015 are installed

**Comment by madoar** [comment]
I believe you've made the changes to the already existing script in the repository right?
I'm not sure if it's worth it to try fixing the script, because it is quite old and fails somehow unexpected (at least to me). 
I would suggest writing a new script based on https://www.reddit.com/r/leagueoflinux/comments/5ukgur/a_revised_guide_for_installing_league_of_legends/, which is a league installation guide for linux, that is regularly updated.

**Comment by Sylvert0** [comment]
I have this error now
![Installer](blob:https://imgur.com/4de450bd-5e20-4f9b-b5b8-7f9c8371d7c1)

**Comment by plata** [comment]
Can you try without `wine.d3dx9();`? Maybe it interferes with the DirectX installation during the setup.

**Comment by Sylvert0** [comment]
No, it's from the installer. It try to install it if u have it or not and i don't know how to manage it

**Comment by plata** [comment]
You can clone the "Scripts" repository and then use you local clone as described in the [wiki](https://github.com/PhoenicisOrg/POL-POM-5/wiki/Repository). If you do that, you can remove the line `wine.d3dx9();` and see if it improves the behavior.
