### ISSUE TITLE
Add the possibility to install a verb in an existing container

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/scripts#534]
Like in POL4. 

Maybe also update Local and Online Installer Script to ask the user which verb he wants to install.

**Comment by Zemogiter** [comment]
About Local/Online Installer, can it be done like selecting languages in https://github.com/PhoenicisOrg/Scripts/blob/master/Applications/Internet/Internet%20Explorer%207.0/Online/script.js ?

**Comment by plata** [comment]
The first thing we need is a list of available verbs. This must be provided from the repository (so in Java, probably `RepositoryManager`). Maybe `getApplication` can do this already.
With this information, the `InstallerScript` should be able to show a list of available verbs as an additional installation step.

**Comment by madoar** [comment]
I agree for this we would first require a queryable list of all available verbs.
The problem here is, that the verbs are kind of bound to an engine type.
I guess it makes no sense to use DirectX 9 with Dosbox or some other system.
So I believe the available verbs need to be queried from the engine, to which the verb can be installed.

If this is the case, then this issue may be linked to https://github.com/PhoenicisOrg/POL-POM-5/issues/1104 and https://github.com/PhoenicisOrg/POL-POM-5/issues/1024

**Comment by plata** [comment]
This can be implemented similarly to engine settings.

**Comment by t0msk** [comment]
What is progress of this request? :) Because it is here since March.

**Comment by plata** [comment]
Not so much...

**Comment by plata** [comment]
I've checked it again. To call the verb from Java, it should implement an interface like the engine tools. However, it's not that easy because the verbs can have parameters (e.g. vk9 has a version parameter).
I see two options:
1. We restrict all verbs such that they can have only one string parameter.
2. An additional class (e.g. `VerbCaller`) implements the interface which contains a method `install()`. This `VerbCaller` could then show a wizard where you can select the verb version (or whatever parameter there might be).

What do you think?

**Comment by Zemogiter** [comment]
The first option sounds easier to do.

**Comment by plata** [comment]
Yes. The question is if it will always be enough.

**Comment by qparis** [comment]
Any java object that can be serialized into a JSON would be enough I guess

**Comment by plata** [comment]
Don't quite understand. Can you elaborate a bit more?

**Comment by qparis** [comment]
We could decide that the verb can have only one argument that is a javascript dictionnary. Then, any Java interface could be passed as an argument (after a objectMapper.writeValue()).

**Comment by plata** [comment]
Understood. But if we want to call that from Java, we would have to know the parameters for every verb. So no generic solution possible. I don't think that's a good idea.

**Comment by ImperatorS79** [comment]
It could also be great to keep track somewhere which verbs have been installed in an existing container (during script installation or afterwards)..

**Comment by madoar** [comment]
I agree with @ImperatorS79, when we allow for the installation of verbs later on we also need to allow for their deinstallation for this we'll need to also know which verbs are installed in a container.

About the input parameters for the verbs:
Is it possible to assume some default parameters for each verb?
If yes we could add the verbs to use these default parameters if no explicit input is provided.

In my mind we want to manage the verbs of a container in via a separate tab in the container details panel.
This tab should contain a list of all available verbs with either an install or an uninstall button.

**Comment by ImperatorS79** [comment]
For vk9 and dxvk, the verb downloads the latest version if no argument is specified.

**Comment by qparis** [comment]
Uninstalling a verb in the general case won’t be possible. You have some case where you’ll need to overuse some files or configuration. 
(Exemple, try to uninstall ie6)

**Comment by ImperatorS79** [comment]
Yes, but for some of them it could be possible.

**Comment by madoar** [comment]
We could leave the uninstallation of verbs for later, but we'll still require a persistent list of all verbs installed in a container to prevents verbs from being installed more than once.

I think such a list should be saved inside the container at the root level.

**Comment by t0msk** [comment]
@qparis Uninstalling is not possible? So if I would like to remove some dll's or fonts, then I had to wipe whole container and install everything again from scratch?

**Comment by madoar** [comment]
@t0msk I believe the reason is, that there may be multiple installed verbs relying on the same dlls.
So if the deinstallation of one verb removes such a dll, the other verb won't work correctly anymore.

**Comment by t0msk** [comment]
@madoar I don't see into it, but I think everythink is possible :) For example you could set dependencies for that verbs, or make some relations between them in JSON.

**Comment by madoar** [comment]
Yes, but using the same dll is just an easy case for a conflict when uninstalling a verb.
What could also happen is that one verb created a configuration file, which another one modified it.
Here it becomes much harder in my opinion to decide what needs to be done.

I agree with you that it is possible to implement the deinstallation of verbs in Phoenicis, the issue is just how much work is it to solve these corner cases, which lead to quite strange effects/bugs for the users?

In addition, it is useful to note that winetricks, according to their [website](https://wiki.winehq.org/Winetricks), doesn't offer functionality to uninstall "things" installed through it by default.

**Comment by ImperatorS79** [comment]
@madoar if multiple verbs override the same dll or the same config file, then it will be broken anyway. For exemple if you try to install d3d11 verb after dxvk verb, then you will be in big trouble.

Maybe a verb could list the wine dll it modifies, so that you cannot install to verb that will modify the same dll (or ask the user if he really wants to override). Again, for simple verb, it should be possible to uninstall it (example

**Comment by madoar** [comment]
I'm not talking about overriding, I'm talking about appending something, modifying something or removing something from the config file.
These actions normally don't lead to something being broken.

**Comment by ImperatorS79** [comment]
But that config file exist before any verb installation then ?

**Comment by madoar** [comment]
My previous examples were just hypothetical.
So I wouldn't like to fix myself on a specific case. 

In my opinion everything is possible with verbs, because we as the developers of Phoenicis don't know what functionality will be developed by other people as verbs for Phoenicis.
In addition we shouldn't forget, that it is not our goal to write a solution that can only be used with tools for wine but also with tools for other engines.

**Comment by t0msk** [comment]
@ImperatorS79 Installing d3d11 after dxvk is not recommended? I didn't know that, and If I install d3d9 after dxvk?

**Comment by plata** [comment]
Please concentrate on the topic (otherwise this will not lead anywhere ;) ).

I think we all agree that the verbs will be listed like engine tools in the container tab. The open question is how the interface should look like. I would suggest to go for the "1 version parameter" solution and enhance it later if we should figure out that it's not sufficient.
As a side note: the scripts must be changed such that they do not call `wine.vcrun2010()` but rather:
```Javascript
var vcrun2010 = new Vcrun2010(wine);
vcrun2010.install();
```

**Comment by qparis** [comment]
> Please concentrate on the topic (otherwise this will not lead anywhere ;) ).

On the contrary, I believe that this debate is really important to understand what a verb is and what a verb is not. This is exactly the difference between a verb (install vcrun2008) and a setting for example (enable / disable GLSL, overide a DLL, ...). Both of these should be customizable. 

> I don't see into it, but I think everythink is possible :) For example you could set dependencies for that verbs, or make some relations between them in JSON.

In theory, yes. In practice, definitely not. You have many proprietary installer (look at POLv4 ie6 verb) that will completely screw up your prefix and you'll have to spend hours on reverse engineering to understand how to reverse it. 

> I think we all agree that the verbs will be listed like engine tools in the container tab. The open question is how the interface should look like. I would suggest to go for the "1 version parameter" solution and enhance it later if we should figure out that it's not sufficient.
> As a side note: the scripts must be changed such that they do not call `wine.vcrun2010()` but rather:
> 
> ```js
> var vcrun2010 = new Vcrun2010(wine);
> vcrun2010.install();
> ```

I don't understand what are the differences

**Comment by plata** [comment]
Sure, the discussion is important. But the topic is about installing a verb and not about uninstalling it (which, like you said, is not really feasible).

Regarding the solution: If we want to call verbs from Java in a generic way, there "install" method should not have different names (vcrun2010, dxvk...) because all verbs implement the same Java interface. Check engine tools as an example.

**Comment by plata** [comment]
I've started some prototyping in #731. Please have a look and share your opinion.
