### ISSUE TITLE
Suggestion: Scripts listed for GPU

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#867]
Based on https://github.com/ValveSoftware/Proton/issues/823 it seems that configuration in https://github.com/PhoenicisOrg/scripts/pull/795 works on platinum for Nvidia users assuming certain driver version and has shader issues on AMDGPU.

Recommends making GPU based scripts meaning to install different configuration for Nvidia and AMDGPU.

**Comment by plata** [comment]
You are free to include an if-else for GPU in your script. Doesn't make much sense to write multiple scripts for this. Especially because the user should not have to care about it.

**Comment by Kreyren** [comment]
@plata Noted

**Comment by Kreyren** [comment]
@plata Abstract: Can't we include this in examples ideally some way to automatically detect which GPU is used by end-user and prompt to user-input if multiple GPUs are detected? I believe that we should make different scripts for each vendor.

**Comment by plata** [comment]
I don't think so. Most of the scripts will work regardless of the GPU. It's only special cases where a distinction might be useful.

**Comment by Kreyren** [comment]
@plata i don't have more info to support this claim. For example OverWatch on AMDGPU requires dxvk-chage and generating state chace, but seems to work no problem on Nvidia OOTB. Same for Dishonored 2 in theory and many other games.

**Comment by plata** [comment]
If it works for both AMD and Nvidia, there's no reason to have a distinction, right?

**Comment by Kreyren** [comment]
@plata Works usually for Nvidia but has issues on AMD. -> AMD requires .dxvk_cache provided since it can't deal with shaders fast enough afaik. Probably needs verification.

**Comment by Tk-Glitch** [comment]
DXVK cache contains zero shader. It contains Vulkan pipelines states (and that's why it's shareable and driver agnostic). The fact that RADV shader compiler is slow has nothing to do with it and is unrelated. Technically, every single game in existence that can make use of DXVK would "run better" with a state-cache since you don't have to recompile that part. You can also upgrade your CPU to make it less of an issue.
However, shaders will need to be recompiled, for each different GPU and each driver update, and there's no way around it.

**Comment by Kreyren** [comment]
@Tk-Glitch Thanks!

**Comment by plata** [comment]
So if it's driver agnostic, the whole point of this issue is invalid which means it can be closed, right?

**Comment by Kreyren** [comment]
@plata Don't have more info to support my claim, will re-open if i find more.
