### ISSUE TITLE
Add FontsSmoothRGB verb

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#912]
Requesting `FontsSmoothRGB` verb that is required for https://github.com/PhoenicisOrg/scripts/pull/908.

**Comment by plata** [comment]
Seems to be pretty straight forward, it's just some registry changes. Have a look at:
https://www.playonlinux.com/en/app-722-POL_Function_FontsSmoothRGB.html

In general it's always a good idea to test this in combination with an app which requires the verb because otherwise you cannot really no if it works.

**Comment by plata** [comment]
It probably makes sense to implement the different fonts smooth types in one single verb, so:
- https://www.playonlinux.com/en/app-722-POL_Function_FontsSmoothRGB.html
- https://www.playonlinux.com/en/app-723-POL_Function_FontsSmoothBGR.html
- https://www.playonlinux.com/en/app-724-POL_Function_FontsSmoothGrayScale.html

**Comment by Zemogiter** [comment]
Try adding these registry tweaks to the script itself.
https://phoenicisorg.github.io/scripts/Develop/script-js/#registry
